### PR TITLE
Add filtering dropdown and cards

### PR DESCRIPTION
**Pull request by adnanademovic**
### Jira Issue(s)
SAAS-340
SAAS-341
SAAS-342
SAAS-343
SAAS-344
SAAS-434
SAAS-447

### Change Log
* Add Filter dropdown
* Add Filter cards

### Notes
* This merges into the release branch
* Does not filter fetched data tables at the moment, just static data ones

### CODE REVIEW

**Comment by mt-foo** [comment]
Here's what I found so far:

* "Show Results" should never be disabled. In the case of empty filter criteria, just dismiss the modal.
* Clicking "Show Results" should dismiss the filter dropdown as well.
* "Filter" button should have a hover state
* The counter design within the "Filter" button and inline with the filter option should match
* Padding to the left and right of the number in the counter should be 4px, not 6px
* Border radius for the counter should be 3px on all corners, not 100px
* Font weight for the counter should be bold, not regular
* Background color for all counters should be `rgb(62, 79, 149)` and the color of the number should be white

Some things I noticed were missing:
 
Screen Shot 2022-03-23 at 8 03 12 AM
When a filter is applied, there should be an applied filter that appears as a badge above the table


Screen Shot 2022-03-23 at 8 02 17 AM
Below a table should be a counter of results designed like the screenshot above.

**Comment by adnanademovic** [comment]
@mt-foo All is addressed, except for the things Alex mentioned will be a different MR.

Just regarding '"Filter" button should have a hover state' - is that an actual hover state, or do you mean when the dropdown is open state? I've implemented the latter, while for the former I have no mockup of what color it should be.

Originally I kept the badges consistent with how they looked in all other Table elements. That was the first query by Scott and I on the Figma, as we already use certain pills for counters everywhere. We got no response on it though. I guess I should have pinged about it elsewhere as well.

**Comment by mt-foo** [comment]
@adnanademovic great! Is there a way I can view an updated storybook of the react component?

I meant the actual hover state, ideally I'd like that to match with how we already do hover states on buttons of the same color, with the background color changing slightly.

Yeah that's my bad, I'm still getting used to communicating in Figma. I'd like to update the counter to match the one in the new design.

**Comment by adnanademovic** [comment]
@mt-foo Hover state is added as well now

**Comment by sestanley13** [comment]
@mt-foo many of these tables extend to the right edge of the screen. Always opening the pop-up to the right may cause issues. How should we accommodate this?

**Comment by alexjmathews** [comment]
https://user-images.githubusercontent.com/12983143/159809796-0b11c493-0dc0-4878-8e70-cfc6b06d8ecc.mov

@sestanley13 yeah i can see why that would potentially become problematic.

**Comment by mt-foo** [comment]
@sestanley13 yeah this is a great shout of an edge case. Ideally it would follow a similar interaction pattern to an HTML5 select, where the dropdown is positioned to always be completely visible on screen.

**Comment by alexjmathews** [comment]
@adnanademovic let's see if we can find an open source package for deciding on position of the popover with respect to the window and implement in a separate MR into the release branch. I think that positioning logic is worth reviewing separately. Maybe something we can make generalizable.

**Comment by adnanademovic** [comment]
@alexjmathews Sounds good to me. I made SAAS-434 as part of the epic to track that.

**Comment by adnanademovic** [comment]
@alexjmathews Just a thought - we might be overthinking this. We manually set anchors for dropdowns/popups. We could have a parameter for tables to specify on which side we want the popups to align.

**Comment by mt-foo** [comment]
@adnanademovic @alexjmathews I'm flexible with how we solve it. Lemme know what y'all uncover

**Comment by adnanademovic** [comment]
Just a heads up: the branch has been rebased for merges that happened in the meantime, and now the dataLoader table on the right filters correctly as well

**Comment by adnanademovic** [comment]
@sestanley13 @mt-foo The moving modals and adjustment to editor position have been added now

**Comment by adnanademovic** [comment]
@sestanley13 @mt-foo Cards have been added as well

**Comment by adnanademovic** [comment]
@sestanley13 @mt-foo Tooltips have been added for cards

**Comment by sestanley13** [comment]
@adnanademovic it looks like the date filters are erroring in this build. It may just be storyboard issue, but this appears when a date is selected:
Screen Shot 2022-03-29 at 10 10 45 AM

Everything else behaving really nicely though!

**Comment by adnanademovic** [comment]
@sestanley13 Can you try to make steps I can replicate?

This issue can be literally anything, and I cannot make it trigger.

**Comment by adnanademovic** [comment]
Rebased to new release branch commit

**Comment by adnanademovic** [comment]
@sestanley13 Timezone chaos, as usual. Should all be good now.

**Pull request merged**
